# Generated by Django 5.0.7 on 2024-08-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoUsuario",
            fields=[
                (
                    "tipo_usuario_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("tipo", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "tipo_usuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("nombre1", models.CharField(max_length=20)),
                ("nombre2", models.CharField(blank=True, max_length=20, null=True)),
                ("apellido1", models.CharField(max_length=20)),
                ("apellido2", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.CharField(max_length=30)),
                ("telefono", models.CharField(max_length=15)),
                ("correo", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "usuario",
                "managed": False,
            },
        ),
    ]
