# Generated by Django 5.0.7 on 2024-08-14 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comuna",
            fields=[
                ("comuna_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "comuna",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "comuna",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "region",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "region",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoInmueble",
            fields=[
                (
                    "tipo_inmueble_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("tipo", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "tipo_inmueble",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="tipousuario",
            options={},
        ),
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("m2_construidos", models.DecimalField(decimal_places=2, max_digits=6)),
                ("m2_totales", models.DecimalField(decimal_places=2, max_digits=6)),
                ("estacionamientos", models.IntegerField()),
                ("habitaciones", models.IntegerField()),
                ("banos", models.IntegerField()),
                ("direccion", models.CharField(max_length=30)),
                ("precio", models.IntegerField()),
                (
                    "comuna",
                    models.ForeignKey(
                        blank=True,
                        db_column="comuna",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="web.comuna",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_column="region",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="web.region",
                    ),
                ),
                (
                    "tipo_inmueble",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="web.tipoinmueble",
                    ),
                ),
            ],
        ),
    ]
