# Generated by Django 5.0.7 on 2024-08-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comuna",
            fields=[
                ("com_id", models.AutoField(primary_key=True, serialize=False)),
                ("com_comuna", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "comuna",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                ("inm_id", models.AutoField(primary_key=True, serialize=False)),
                ("inm_nombre", models.CharField(max_length=50)),
                ("inm_descripcion", models.TextField(blank=True, null=True)),
                (
                    "inm_m2_construidos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "inm_m2_totales",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("inm_estacionamientos", models.IntegerField(blank=True, null=True)),
                ("inm_habitaciones", models.IntegerField(blank=True, null=True)),
                ("inm_banos", models.IntegerField(blank=True, null=True)),
                (
                    "inm_direccion",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("inm_precio", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "inmueble",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("reg_id", models.AutoField(primary_key=True, serialize=False)),
                ("reg_region", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "region",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tipo_Inmueble",
            fields=[
                ("ti_id", models.AutoField(primary_key=True, serialize=False)),
                ("ti_tipo", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "tipo_inmueble",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tipo_Usuario",
            fields=[
                ("tu_id", models.AutoField(primary_key=True, serialize=False)),
                ("tu_tipo", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "tipo_usuario",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="TipoUsuario",
        ),
    ]
