# Generated by Django 5.0.7 on 2024-08-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_comuna_region_tipoinmueble_alter_tipousuario_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tipousuario",
            table=None,
        ),
    ]
